### ISSUE TITLE
Access Message Tag directly from MessageReceivedEventArgs

### ISSUE THREAD

**Issue by DrDerp20** [DarkRiftNetworking/DarkRift-Networking#13]
### Quick Description
Instead of having to do a MessageReceivedEventArgs.GetMesssage just to get the message's tag, MessageReceivedEventArgs should expose the tag by itself.

### Explaination
The main reason for this change would be so that x amount of Message objects are not being created for every MessageReceived just to check the tag, but instead the Message object is only created where and when it needs to be.

I cannot speak for others, but my current use cases go something like this for every MessageReceived method:
```csharp
private void MessageReceived (object sender, MessageReceivedEventArgs e)
{
	using (Message message = e.GetMessage() as Message)
	{
		switch (message.Tag)
		{
			case Tags.useMessageInSwitch:
				UseMessageInMethod (message);
				break;
		}
	}
}
```
The proposed change would result in usage like this:
```csharp
private void MessageReceived (object sender, MessageReceivedEventArgs e)
{
	switch (e.Tag)
	{
		case Tags.useMessageInSwitch:
			using (Message message = e.GetMessage())
			{
				// message logic 
			}
			break;
		case Tags.useMessageInMethod:
			using (Message message = e.GetMessage ())
			{
				MessageInMethod (message);
			}
		case Tags.useMessageReceivedEventArgsInMethod:
			UseMessageReceivedEventArgs ();
			break;
	}
}
private void UseMessageInMethod (Message message)
{
	// message logic
}
private void UseMessageReceivedEventArgs InMethod (MessageReceivedEventArgs e)
{
	using (Message message = e.GetMessage())
	{
		// message logic
	}
}
```

**Comment by proepkes** [comment]
Another option could be to get rid of that large switch-case and instead add MessageHandler-methods per tag to the connection. 
Example:

```
  private void OnPlayerConnected(object sender, ClientConnectedEventArgs e)
        {
            e.Client.AddHandler(Tags.CreateRoom, HandleCreateRoom)
        }

private void HandleCreateRoom(object sender, Message message)
{
 var data = message.Deserialize<CreateRoomPacket>();
  // handle data
}
```

**Comment by JamJar00** [comment]
This sounds like a good idea, although messages are quite cheap to produce (with recycling) there's still an overhead. I'll see about implementing this for a future version!

@proepkes DarkRift 2 did have this in an early beta/just before the beta but it was removed. I can't remember the exact reasons why, but I think it was because there was a fairly substantial penalty hit compared to having a single, user-defined switch case statement and that isn't too hard to add yourself compared to this which adds a lot of complexity internally.

**Comment by JamJar00** [comment]
This is completed (the issue not the extension) and will be available in a future minor release!
