### ISSUE TITLE
`ReadRawInto` produces incorrect data

### ISSUE THREAD

**Issue by martindevans** [DarkRiftNetworking/DarkRift-Networking#15]
### Quick Description

ReadRawInto produces incorrect results.

### Explanation

I asked on Discord if the following _should_ be equivalent, Jamster confirmed that they should:

```
for (var i = 0; i < length; i++)
    buffer[i] = reader.ReadByte();
```

```
reader.ReadRawInto(buffer, 0, length);
```

However, using the ReadRawInto version produces different results.

From looking at the decompilation of DarkRiftReader it looks like this _may_ be because the `BlockCopy` parameter for position does not take into account the `dataoffset` field.

This seems to happen completely reliably in my own code when swapping between the two (an integration for Dissonance Voice Chat). I haven't reduced that down to a smaller test case, but I think reading from a DarkRiftReader with an offset should produce the issue.

**Comment by JamJar00** [comment]
This should be fixed in the next release. Thanks for finding it!
