### ISSUE TITLE
Request: Add Server Status Feedback

### ISSUE THREAD

**Issue by HomerJohnston** [DarkRiftNetworking/DarkRift-Networking#19]
### Quick Description
The DarkRiftServer class needs some way to determine if it successfully started and/or if it is currently listening for connections.

Possible ideas:

1. Make **DarkRiftServer.Start()** return bool, or some kind of new enum like **ServerStartErrorCode { Success, Failure, GenericError}**
2. If server starting might ever need to be asynchronous, instead or also add a new **StartInBackground(...)** method signature with an OnComplete callback
3. Implement something like **bool DarkRiftServer.Listening { get; }** which returns whether or not the server is currently listening for connections

Use cases:

1. If the server fails to start (e.g. because the port was already in use) I want to inform the user with more information
2. I have a "start server" button which I want to disable whenever the server is successfully started and listening for connections, and maybe also when it is in the process of starting (if I'm somehow starting the server process asynchronously, if that might ever be worth implementing)

**Comment by JamJar00** [comment]
These all sound very good options, thanks for putting the time into writing this issue!

**Comment by JamJar00** [comment]
Done! This should be in the next release.

For information, I have added a Boolean response the `Start` method and have added a `Listening` variable.
