### ISSUE TITLE
ConnectInBackground issue

### ISSUE THREAD

**Issue by Deusald** [DarkRiftNetworking/DarkRift-Networking#22]
### Quick Description
When we try to connect and disconnect using ConnectInBackground and try to send reliable packages between the game will eventually freeze with exception "Operation in progress". Also after n'th connection via ConnectInBackground the reliable packages are not coming.
Edit:
Maybe it also matters that I'm sending reliable message in a caller (ConnectCompleteHandler). So it is send immediately after caller is executed with null exception.

**Comment by JamJar00** [comment]
I've added our potential fix for this to the next version. If this seems to fix it permanently we can close this, but let's leave it open until it's definitely fixed.

**Comment by JamJar00** [comment]
Can you confirm if you've had this issue since @Deusald?

**Comment by Deusald** [comment]
@JamJar00 The bug has not happened to me in current versions. So I can say it's fixed for sure ;)
