### ISSUE TITLE
Write(bool[]) to ReadBools() results in array of bools being reversed.

### ISSUE THREAD

**Issue by kennedyalec** [DarkRiftNetworking/DarkRift-Networking#27]
When I create a message and send an array of bools to a client the client gets a reversed version of the array.  Same thing happens with message from client to server.  This is testing on the same PC and does not happen with any other array types.

#### For Issues
-Embedded server
-Windows PC
-Seems like it may be a bit packing or endian-ness issue.

**Comment by kennedyalec** [comment]
Workaround: I can simply read the resulting array backwards.

**Comment by JamJar00** [comment]
This definitely looks like a bug! Thanks for finding it!

**Comment by JamJar00** [comment]
Fixed in the next release!
