### ISSUE TITLE
Issues in the documentation

### ISSUE THREAD

**Issue by Rakinare** [DarkRiftNetworking/DarkRift-Networking#3]
### Quick Description
"And change the tag parameter in both constructor calls to Tags.SpawnPlayerTag."
https://darkriftnetworking.com/DarkRift2/Docs/2.0.0/html/3fa31013-daf8-49eb-a875-fdbc715cbf70.htm

"That's actually poor phrasing, it's refering to the Message.Create calls" - Jamster

"DarkRiftReader reader = e.Message.GetReader();" - reader is declared twice at the spawn packets code
https://darkriftnetworking.com/DarkRift2/Docs/2.0.0/html/3fa31013-daf8-49eb-a875-fdbc715cbf70.htm

**Comment by JamJar00** [comment]
Thanks for taking the time to create the issue and for having the patience to work around them!

Sorry that they haven't already been sorted.

**Comment by JamJar00** [comment]
The issues you raised should now be fixed on the website If you find any more, or have any other general improvements, please don't hesitate to add new issues for them!

Jamie
