### ISSUE TITLE
Darkrift Socket Exception: Existing Connection was closed

### ISSUE THREAD

**Issue by Umar559** [DarkRiftNetworking/DarkRift-Networking#32]
### Quick Description
I face Socket  Exception on global server... "Existing Connection was  forcefully closed by remote host."

### Explaination
UnHandle Socket Exception occur "

> **A connection Attempt failed because connection party did not respond**
> **Existing Connection was forcefully closed by remote host**

then game in mobile is stuck and server not response any client.

How fix this darkrift bug

#### For Feature Requests

![socket error](https://user-images.githubusercontent.com/40425266/41651738-b4cc2ad8-749a-11e8-844a-2dbcf2c3c0fd.png)
![whatsapp image 2018-06-18 at 1 26 45 pm](https://user-images.githubusercontent.com/40425266/41651741-b6676b50-749a-11e8-9d5e-ae25da833ed2.jpeg)

**Comment by JamJar00** [comment]
Hey,

Thanks for finding this! It looks like you're using an old version of DarkRift right now which is making a bit tricky to find the source of the problem, can you update and repost some screenshots or log files please?

**Comment by JamJar00** [comment]
Did updating your DarkRift version solve this issue for you or are you still having problems?

**Comment by Umar559** [comment]
Hi, James I upgrade the DrakRift version on both side (client,server). and it's work **_Perfectly_**... still no connection error receive....   Thanks

**Comment by JamJar00** [comment]
Awesome! Thanks for getting back to me! 🙂
