### ISSUE TITLE
IP Address Reset

### ISSUE THREAD

**Issue by MrGadget1024** [DarkRiftNetworking/DarkRift-Networking#33]
### Quick Description
IP address set in inspector gets ignored / reset, and isn't used.

### Explaination
This is for embedded server, UnityServer.cs address field.
When I press play, the component appears to be reloaded and the IP goes back to 0.0.0.0.

I worked around it by hardcoding the IP into line 327:
`ServerSpawnData spawnData = new ServerSpawnData(IPAddress.Parse("127.0.0.1"), port, ipVersion);`

#### For Issues
- Embedded Server Unity 2017.4.1f1 LTS
- Set an IP address in the field and press play

**Comment by JamJar00** [comment]
Hi MrGadget,

This should no longer be a problem since XmlUnityServer replaces UnityServer and doesn't have this issue. Thanks for finding it!

Jamie
