### ISSUE TITLE
Feature Request: Writing/reading arrays of IDarkRiftSerializable

### ISSUE THREAD

**Issue by hiimada** [DarkRiftNetworking/DarkRift-Networking#34]
Hey Jam, could you consider adding an overload to DarkRiftWriter.Write() and DarkRiftReader.Read() for writing/reading arrays of IDarkRiftSerializable objects too? Would be really quite handy, and I don't think its too much work to implement considering you already have them for the other data types and could probably do it with a simple for loop in the overload.
Thanks!

**Comment by JamJar00** [comment]
Sure!

**Comment by JamJar00** [comment]
Should be added in next release.
