### ISSUE TITLE
Feature Request: Packet Writer Reserve Space

### ISSUE THREAD

**Issue by martindevans** [DarkRiftNetworking/DarkRift-Networking#36]
### Quick Description
Add the ability to reserve space in a packet writer which can be written into later

### Explaination
In other systems when writing variable length data into a packet I will reserve some space for a length prefix, write the data, and then go back and write the length prefix. This appears to be impossible with Dark Rift.

I imagine an API like this:

```
DarkRiftWriter writer;

//Reserve some space, this returns a struct which can write back into the correct position in the buffer
//Possibly there could be a counter in the writer which causes an exception if you try to send a message with unused reserved space
var reserved = writer.ReserveInt();

//write other stuff
...

//Write into the reserved space
reserved.Write(an_integer);
```

**Comment by JamJar00** [comment]
Neat idea! Sounds good 🙂 

I guess there's a spectrum of ways to implement this: on one side you could have an entire DarkRiftWriter returned for the reserved space, on the other you could just return the current position and later set the position and write.

I'll have a look into it!

**Comment by Jawsarn** [comment]
This is the most awesome thing in the whole world, we need this yesterday! 🤤 💯 🐐

**Comment by JamJar00** [comment]
Implemented! You can now reserve space in a writer and there is a new, modifiable Position property you can use to rewind the writer back to the location reserved.

This will be in the next version.
