### ISSUE TITLE
Suggestions for the documentations

### ISSUE THREAD

**Issue by Rakinare** [DarkRiftNetworking/DarkRift-Networking#4]
### Quick Description
https://darkriftnetworking.com/DarkRift2/Docs/2.0.0/html/24f9d464-af6c-479f-a14f-d91781a60579.htm

At the bottom, please change 
"Finally add this line to the bottom of your SpawnPlayer method:"

to 
"Finally add this line at the bottom of your last call in the SpawnPlayer method:"

also "Have a go at writing the logic for this yourself, "
to "Have a go at writing the logic to receive the position data yourself, "

Some small adjustments to make it just a little more newb friendly.

Thanks!

Regards,
Rakinare

**Comment by JamJar00** [comment]
Thanks once again for your suggestions 🙂

**Comment by JamJar00** [comment]
Docs now have these changes! Thanks 🙂
