### ISSUE TITLE
Feature: DarkRiftReader change reading position

### ISSUE THREAD

**Issue by Jawsarn** [DarkRiftNetworking/DarkRift-Networking#41]
(very similar to others, but not exactly same, so I opened a new)
It would be nice to be able to change the "position" of DarkRiftReader, so you can skip without using ReadRawInto. Something like a SetPosition(position), or SkipBytes(bytes) would work. If you have conditional buffered data in your messages it would be nice to skip reading it :)

**Comment by JamJar00** [comment]
The Position property is now modifiable in readers so you can skip/rewind as you need!

This will be in the next version 🙂
