### ISSUE TITLE
The DarkRiftWriter/Reader bool[] functions doesn't work.

### ISSUE THREAD

**Issue by Jawsarn** [DarkRiftNetworking/DarkRift-Networking#53]
The DarkRiftWriter/Reader boolean array functions doesn't work.

Using Unity embedded server.
To recreate:
On client Create bool[] myArray = bool[8];
Fill with values of true
Use DarkRiftWriter.Write(bool[]) and send message to server.

On server read message
Use DarkRiftReader.ReadBooleans(); to fill bool[] outArray
No values are true in outArray.

**Comment by JamJar00** [comment]
Confirmed as a bug in DarkRiftReader, it wasn't accounting for the offset of data in the backing array. This will be fixed in the next version
