### ISSUE TITLE
Error starting and stopping a server and then recreating it throws error that is below

### ISSUE THREAD

**Issue by reignofdave** [DarkRiftNetworking/DarkRift-Networking#55]
Thanks for creating an issue/feature request! Please use the template below to ensure you have all the necessary information.

### Quick Description
Getting this error When trying to dispose of a server and recreate it via xml monobehaviour in unity.

```
DarkRiftServer        A listener threw an exception while starting, the server can't be started.
                                 System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted.
```

### Explanation

Code to stop the server

```csharp
    /// <summary>
        ///     Closes the server.
        /// </summary>
        public void StopServer()
        {
            DarkRiftServer.Dispose();
            DarkRiftServer = null;
        }
```

#### For Issues
- Conditions it occurred (Unity based server/standalone server, Unity version, hosted/local development, etc.)
1. Create a server from the xml unity server
2. Dispose of the DarkRiftServer object
3. Create server again

**Comment by JamJar00** [comment]
Fixed in the next version! 🙂
