### ISSUE TITLE
Issue - Incorrect Documentation for DarkRift 2

### ISSUE THREAD

**Issue by NixAJ** [DarkRiftNetworking/DarkRift-Networking#8]
Description:
On the given page: https://darkriftnetworking.com/DarkRift2, there is an example of a template for a plugin, however the constructor has a different name than the class. The example is also missing "#Include Darkrift", in order to work with the LogType.

**Comment by JamJar00** [comment]
This should now be fixed and live! I've elected to omit the using statements for the libraries since is seems like slightly unnecessary clutter in the example 🙂 

Thanks for pointing them out!
